name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version to deploy (e.g. 1, 1_fix)'
        required: true
        type: string
      issue_number:
        description: 'Issue number'
        required: true
        type: number

jobs:
  deploy:
    name: Deploy Release ${{ inputs.release_version }} to Production
    runs-on: ubuntu-latest

    env:
      REGISTRY_NAME: crph4codaco7ibpqes0d
      RELEASE_VERSION: ${{ inputs.release_version }}
      CLOUD_ID: b1gr908prd2uo9dahreb
      FOLDER_ID: b1gre28ftdr7otqsp4c7

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Yandex.Cloud CLI
        run: |
          curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH

      - name: Authenticate with Yandex.Cloud
        env:
          YC_SA_KEY_JSON: ${{ secrets.YC_SA_KEY_JSON }}
        run: |
          echo "$YC_SA_KEY_JSON" > key.json
          yc config set service-account-key key.json
          yc config set cloud-id $CLOUD_ID
          yc config set folder-id $FOLDER_ID

      - name: Log in to Yandex Container Registry
        run: |
          yc container registry configure-docker

      - name: Check image exists
        run: |
          IMAGE="cr.yandex/${REGISTRY_NAME}/app:${RELEASE_VERSION}_latest"
          echo "Checking if image exists: $IMAGE"

          if docker manifest inspect "$IMAGE" > /dev/null 2>&1; then
            echo "✅ Image exists: $IMAGE"
          else
            echo "❌ Image not found: $IMAGE"
            exit 1
          fi

      - name: Deploy to production server
        uses: appleboy/ssh-action@v1.0.3
        env:
          REGISTRY_NAME: ${{ env.REGISTRY_NAME }}
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SERVER_SSH_PRIVATE_KEY }}
          envs: REGISTRY_NAME,RELEASE_VERSION
          script: |
            IMAGE="cr.yandex/${REGISTRY_NAME}/app:${RELEASE_VERSION}_latest"

            yc config set service-account-key <(echo '${{ secrets.YC_SA_KEY_JSON }}')
            yc container registry configure-docker

            docker pull "$IMAGE"

            docker stop shri-infra || true
            docker rm shri-infra || true

            docker run -d --name shri-infra -p 3000:3000 "$IMAGE"

      - name: Add comment to release issue
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ inputs.issue_number }}
          body: |
            ✅ **Release deployed to production**

            - Image: cr.yandex/${{ env.REGISTRY_NAME }}/app:${{ env.RELEASE_VERSION }}_latest
            - Host: `${{ secrets.PROD_SERVER_IP }}`
            - Deployed by: @${{ github.actor }}
